### ISSUE TITLE
Gaps in chains containing CYM residues

### ISSUE THREAD

**Issue by IAlibay** [Amber-MD/pdb4amber#60]
Hi,

I have noticed that pdb4amber appears to be unable to indentify CYM residues leading to it reporting the presence of gaps in protein chains containing them.

As a test for this I created ALA - CYN - ALA peptides (where N is either S, X or M) in leap, saved them as PDBs and then parsed them through pdb4amber. In the case of the CYS and CYX containing peptides everything seems ok, but with CYM pdb4amber finds a gap between the two alanines.

Seems that the issue is that residue.py doesn't have entries for CYM. Adding them in seems to fix this problem, but I am not sure if that will unintentionally break other things.

**Comment by hainm** [comment]
hi @IAlibay, your change is correct. The issue you reported is current limitation of pdb4amber.

**Comment by IAlibay** [comment]
Ok, it's its a tiny change but I can create a pull request if needed.

One related question, should there be a change in the ``find_disulfide`` function of pdb4amber.py to allow for the possibility of CYM? I might be misunderstanding line 258, but from what I gather, the code currently might pick up a CYS or CYX -> CYM bond, but not a CYM -> CYM?

**Comment by hainm** [comment]
yes, do feel free to make a PR for both. A test will be needed. thanks.

https://github.com/Amber-MD/pdb4amber/blob/master/tests/test_cmd.py

**Comment by hainm** [comment]
Add CYM in #64.

**Comment by jiucenglou** [comment]
> Add CYM in #64.

It looks like there is regression in AmberTools20/21 about this . 
Could you suggest what is the proper way to fix the pdb4amber.py in AmberTools20/21 ? 

    test@localhost:/opt/amber$ find ./ -iname pdb4amber.py
    ./amber20/lib/python3.8/site-packages/pdb4amber-20.1-py3.8.egg/pdb4amber/pdb4amber.py
    ./amber20_src/AmberTools/src/pdb4amber/pdb4amber/pdb4amber.py
    ./amber20_src/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/pdb4amber.py

**Comment by hainm** [comment]
@jiucenglou 

Either:
- Update the source code in ./amber20_src/AmberTools/src/pdb4amber/pdb4amber/pdb4amber.py and run cmake again
- Update the final destination in ./amber20/lib/python3.8/site-packages/pdb4amber-20.1-py3.8.egg/pdb4amber/pdb4amber.py. 

I suggest to update the source code. 

HOWEVER, per @dacase 

> `CYM` residues should never form disulfide bonds
