### ISSUE TITLE
gap warnings which skipping residues

### ISSUE THREAD

**Issue by nitroamos** [Amber-MD/pdb4amber#61]
I'm getting output which looks like this:

```
---------- Gaps (Renumbered Residues!)
gap of 3.776522 A between ACE 1 and SER 3
gap of 4.321198 A between PRO 2 and ILE 4
gap of 3.342821 A between SER 3 and GLU 5
...
gap of 3.714803 A between ASP 40 and NME 42
gap of 12.587828 A between MET 41 and LEU 44
gap of 11.500311 A between NME 42 and ALA 45
gap of 6.603188 A between ACE 43 and LEU 46
...
```
when I run this `pdb4amber -i %s -o amber.pdb`

Is there something wrong with my pdb or can I just ignore these warnings?

Thanks!

**Comment by hainm** [comment]
hi, can you share the pdb file (or a part of it)? thanks.

**Comment by nitroamos** [comment]
it looks like maybe the problem is that this code:

            if atom.name in [
                    'CA',
            ] and atom.residue.name in RESPROT:
                CA_atoms.append(i)
            if atom.name == 'C' and atom.residue.name in RESPROT:
                C_atoms.append(i)
            if atom.name == 'N' and atom.residue.name in RESPROT:
                N_atoms.append(i)

requires every residue to have all 3 atoms: CA, C, and N whereas ACE is missing CA and NME is missing N. The problem is that then these lists become offset from each other (`C_atoms[i]` and `N_atoms[i]` are not necessarily in the same residue). Some solutions:

- you could require that all 3 atoms are present before adding any of them to their respective lists
- you could use resnum to put backbone atoms in the same set and then update the gap detection code to ignore situations where one of the atoms is missing.

I can't provide the pdb I used... I'll make another one.

**Comment by hainm** [comment]
>  I'll make another one.

yeah, anything that could help reproduce the issue. thanks.

**Comment by nitroamos** [comment]
here you go. when I run on the attached pdb, I get this output:

```
----------Chains
The following (original) chains have been found:
A

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
None

---------- Gaps (Renumbered Residues!)
gap of 4.704592 A between ACE 1 and GLU 3
gap of 4.473066 A between GLY 2 and THR 4
gap of 4.626615 A between GLU 3 and THR 5
gap of 4.694552 A between THR 4 and THR 6
gap of 4.647272 A between THR 5 and GLU 7
gap of 4.125350 A between THR 6 and ALA 8
gap of 4.689811 A between GLU 7 and VAL 9
gap of 3.330541 A between ALA 8 and ASP 10
gap of 4.688324 A between VAL 9 and ALA 11
gap of 3.337582 A between ASP 10 and ALA 12
gap of 3.161435 A between ALA 11 and THR 13
gap of 3.473833 A between ALA 12 and ALA 14
gap of 2.812765 A between THR 13 and NME 15
gap of 7.636767 A between ALA 14 and GLN 17
gap of 8.120967 A between NME 15 and TYR 18
gap of 3.974235 A between ACE 16 and ALA 19
gap of 3.661022 A between GLN 17 and ASN 20
gap of 3.867531 A between TYR 18 and ASP 21
gap of 3.691565 A between ALA 19 and ASN 22
gap of 3.891676 A between ASN 20 and GLY 23
gap of 5.696070 A between ASP 21 and VAL 24
gap of 6.861075 A between ASN 22 and ASP 25
gap of 7.262708 A between GLY 23 and GLY 26
gap of 7.728763 A between VAL 24 and GLU 27
gap of 7.535883 A between ASP 25 and TRP 28
gap of 7.593780 A between GLY 26 and THR 29
gap of 7.981676 A between GLU 27 and TYR 30
gap of 7.850106 A between TRP 28 and ASP 31
gap of 7.418567 A between THR 29 and ASP 32
gap of 6.416094 A between TYR 30 and ALA 33
gap of 3.811090 A between ASP 31 and THR 34
gap of 3.521355 A between ASP 32 and LYS 35
gap of 5.875857 A between ALA 33 and THR 36
gap of 6.680768 A between THR 34 and PHE 37
gap of 7.744919 A between LYS 35 and THR 38
gap of 7.705114 A between THR 36 and VAL 39
gap of 7.800273 A between PHE 37 and THR 40

---------- Mising heavy atom(s)

None
```



[output.pdb.txt](https://github.com/Amber-MD/pdb4amber/files/2220804/output.pdb.txt)

**Comment by hainm** [comment]
hi, just to be clear: is the output pdb is ok and this is only matter of
warning? thanks.

**Comment by nitroamos** [comment]
Yes, pdb should be fine. It's just a 1pga that I downloaded, removed some residues, placed ACE/NME caps, and then ran pdb4amber.

According to the Amber manual maybe I should add a TER record, but that seems unrelated to this problem?

**Comment by hainm** [comment]
hi @nitroamos, please see the updated #70.
With your attached system, I get bellow output

```
---------- Gaps (Renumbered Residues!)
gap of 7.636767 A between ALA 14 and GLN 17
```

vs. old code
```
---------- Gaps (Renumbered Residues!)
gap of 4.704592 A between ACE 1 and GLU 3
gap of 4.473066 A between GLY 2 and THR 4
gap of 4.626615 A between GLU 3 and THR 5
gap of 4.694552 A between THR 4 and THR 6
gap of 4.647272 A between THR 5 and GLU 7
gap of 4.125350 A between THR 6 and ALA 8
gap of 4.689811 A between GLU 7 and VAL 9
gap of 3.330541 A between ALA 8 and ASP 10
gap of 4.688324 A between VAL 9 and ALA 11
...
```

Let me know if there is other issues and sorry for the long delay.

**Comment by hainm** [comment]
cc @dacase  about this case.
