### ISSUE TITLE
histidine typing

### ISSUE THREAD

**Issue by nitroamos** [Amber-MD/pdb4amber#69]
I'm having some trouble with this logic:

https://github.com/Amber-MD/pdb4amber/blob/2a3afafaa0cd1990c9b227282335a45d7e7dd96e/pdb4amber/pdb4amber.py#L127-L134

I've got a pdb which already has histidines typed (i.e., HIE, HID, HIP), but if I add the `--nohyd` parameter then all my histidines are converted to `HIS`.

I have two suggestions:

1. remove the last clause in the `if` block. If you don't see any hydrogens, just leave the resname alone instead of converting to `HIS`.
2. my reason for removing hydrogens is I'm having trouble getting other amber tools to accept my hydrogen names #67 . Rather than renaming them, I'm going to try removing them altogether. My problems with the correct hydrogen names makes me worry about checking hydrogen names as in the code snippet above. Would it be safer not to assume that, for example, HIE's hydrogen is named `HD2`? That is, for `HID` require both `HD?` hydrogens?

**Comment by nitroamos** [comment]
I don't want to use `--reduce` because I want to choose protonation states before I invoke `pdb4amber`.

I don't have a test case with an `HD1` in `HIE` or `HE2` in `HID`. Maybe that never happens. For whatever it's worth, I've attached an example with a bunch of HIS residues.


[amber.pdb.gz](https://github.com/Amber-MD/pdb4amber/files/2562052/amber.pdb.gz)

**Comment by hainm** [comment]
@dacase 

> 1. Why is HE1 present in line 127 above?  Presence or absence of that hydrogen seems irrelevant.

remove that HE1 in #73 

> 2. I agree that we should not revert to 'HIS' if no protons are present, but rather leave as is.

also in #73 

Thanks @nitroamos  for your suggestion.
